### ISSUE TITLE
City Bridge Trust Application: complete the online application

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/DLP#107]
### Background

We are applying to City Bridge trust for a large grant: https://github.com/CodeYourFuture/grants/issues/1

### Acceptance criteria

- [ ] Complete the online application based off of the document we have work on

### Stakeholder

Liliana

### Approver

Amy

**Comment by AmyCYF** [comment]
https://docs.google.com/spreadsheets/d/1g5AAqjXElqN-QbulCZz7NITXKjhhlMT6N_FpoVobMMw/edit#gid=0
https://naccom.org.uk/wp-content/uploads/2016/04/firststepsinmonitoringandevaluation-738-746.pdf
https://docs.google.com/spreadsheets/d/1b3l51Z6GOVIKxxJnIg-uk9rmeM8BrrNy/edit#gid=283390899

**Comment by kfklein15** [comment]
@lilianabermudes , could  Amy get your approval by the end of next week (19th July), so she can work on this when she's back from her holiday? Thanks

**Comment by lilianabermudes** [comment]
I asked G and Sally to help finishing the missing part.

**Comment by AmyCYF** [comment]
Reference Number: 25622
