### ISSUE TITLE
Onboarding for trainee management

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/DLP#126]
### Background

As Dara-emma will be managing the trainees for the Sheffield DLP, I will be onboarding her.

### Acceptance criteria

- [x] All relevant documents and forms shared with DE
- [x] Access to Whatsapp web
- [x] DE understands the flow of communication with the trainees

### Owner

Dara-emma

### Stakeholder

none

### Approver

Amy

**Comment by AmyCYF** [comment]
Documentation: 

- [trainee lifecycle](https://miro.com/app/board/uXjVMk16md4=/)
- [Expression of interest sheet](https://docs.google.com/spreadsheets/d/1rTw_uXkLVQX4eiYv_THveLW0qUYPEyTyIFU9c0v3IiQ/edit#gid=1515935725)
- [Sign up form](https://docs.google.com/spreadsheets/d/1AIFXGoZQ_fFJJJiGEGxoCM5oO7heQIWKY9VMPGqpYb0/edit#gid=528555313)
- [Templates](https://drive.google.com/drive/folders/1mVWkLCrdPIKE_4Z7RU6Y1K6-GwZG2oRg)

**Comment by emcglackenr1** [comment]
Can we mark this as complete? @AmyCYF
