### ISSUE TITLE
EXL volunteers for London Cohort

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/DLP#205]
- [x] reach out to EXL volunteers for the London cohort
- [ ] Set up the training for these voluntees
- [x] include Halden to do this training

List of volunteers: https://docs.google.com/spreadsheets/d/1EqPeH1IYn31-jyvn-UnZoU34NMyHmQkh/edit?gid=34592523#gid=34592523

**Comment by AmyCYF** [comment]
@haldenb allocating this ticket to you :)

**Comment by AmyCYF** [comment]
@haldenb have all the volunteers been onboarded? Can I close this ticket?

**Comment by haldenb** [comment]
Unfortunately not I am still waiting on a reply from Maya in the main EXL mail thread
