### ISSUE TITLE
Review LOs with Sally

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/DLP#247]
https://docs.google.com/document/d/1YVhj1ZpbUfVGhM9LJA-P9JctlDCUpv3cwmwH6taFNr0/edit

**Comment by AmyCYF** [comment]
@SallyMcGrath I have [updated the learning objectives](https://docs.google.com/document/d/1pa3phokyW9hZC6Hhau-Vp_FTChWHDdHFW1WKXAtJu6Y/edit) to merge our changes and removed the PMC language.
Please could you review these and let me know if you have any changes?

**Comment by SallyMcGrath** [comment]
@AmyCYF these are so much better. This is really a brilliant improvement!! Thank you so much for this.
