### ISSUE TITLE
review DLP specific competencies

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/DLP#248]
@SallyMcGrath  to Review the DLP specifice additions to the [Tech Ed Mentor competencies sheet](https://docs.google.com/document/d/1n4vj4zdjKoxeIkV4RPuHKMCMcG0VzgKCgiQNql_TJyw/edit#heading=h.aujjsmrg1d7) and provide feedback to @AmyCYF 

These have been added so that we can attribute volunteer badges to these roles

**Comment by SallyMcGrath** [comment]
BTW I did review this -  unassigning myself until there's new work to do
